[package]
name = "metadata"
version = "0.1.0"
authors = ["RanolP <public.ranolp@gmail.com>"]
edition = "2018"

[dependencies]
node = { path = "../node" }
runtime_facade = { path = "../runtime_facade" }